image: tetraweb/php

before_script:  
  #- apt-get update && apt-get install -y git
  #- composer self-update
  #- composer install --prefer-dist --no-interaction

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: 
  #- ./vendor/bin/phpcs --error-severity=1 --warning-severity=8 --extensions=php demo.php
  - echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  before_script:
        # setup ssh
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - chmod 0600 ~/.ssh/id_rsa
        - '[[ -f /.dockerenv ]] && echo -e "Host *ntStrictHostKeyChecking nonn" > ~/.ssh/config'
        - ssh-keyscan $DEV_HOST >> ~/.ssh/known_hosts
  script:
    - ssh root@$DEV_HOST "cd /var/www/html/new/firstproject && git checkout . && git pull origin live  && chown -R www-data:www-data /var/www/html/new/firstproject"
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com


deploy_prod:
  stage: deploy
  script:
    - git remote set-url production https://$GIT_CI_USER:$GIT_CI_PASS@github.com/prajapatisagar/gitlabexample.git
    - git fetch origin
    - git push --mirror https://$GIT_CI_USER:$GIT_CI_PASS@github.com/prajapatisagar/gitlabexample.git
    - git push --prune https://$GIT_CI_USER:$GIT_CI_PASS@github.com/prajapatisagar/gitlabexample.git +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
  - live