image: tetraweb/php


before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - git remote set-url staging ssh://root@git.usstats.org:/var/www/html/repo/helloworld.git
    #- git config --global user.email "admin@example.com"
    #- git config --global user.name "Administrator"
    - git fetch origin
    #- git push -u production master -f
    #- git push -u production live -f
    - git push --mirror ssh://root@git.usstats.org:/var/www/html/repo/helloworld.git
    - git push --prune ssh://root@git.usstats.org:/var/www/html/repo/helloworld.git +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com


deploy_prod:
  stage: deploy
  script:
    - git remote set-url production https://$GIT_CI_USER:$GIT_CI_PASS@github.com/prajapatisagar/gitlabexample.git
    #- git config --global user.email "admin@example.com"
    #- git config --global user.name "Administrator"
    - git fetch origin
    #- git push -u production master -f
    #- git push -u production live -f
    - git push --mirror https://$GIT_CI_USER:$GIT_CI_PASS@github.com/prajapatisagar/gitlabexample.git
    - git push --prune https://$GIT_CI_USER:$GIT_CI_PASS@github.com/prajapatisagar/gitlabexample.git +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
  - live